<?php

declare(strict_types=1);

namespace App\Filament\Resources;

use App\Filament\Resources\LandingPageResource\Pages;
use App\Models\Category;
use App\Models\LandingPage;
use App\Models\Product;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

/**
 * Minimal v1 admin for "Best X" landing pages (Spec 027 §8).
 *
 * Pages are generated by `pw2d:generate-landing-page` — this resource exists so
 * an owner can review a draft, tweak intro/pick prose/FAQs, and PUBLISH without
 * re-running AI generation (the publish toggle is a plain status write, no AI
 * call). Picks are algorithmically selected (App\Actions\SelectLandingPagePicks)
 * so the repeater only allows editing the AI-written prose per pick, not adding/
 * removing/reordering rows — that would silently break the "picks are chosen by
 * DATA, not by the AI/admin" guarantee the whole page's E-E-A-T claim rests on.
 *
 * Tenant-scoped automatically: `LandingPage` uses `BelongsToTenant`, and (unlike
 * `TenantResource`) this resource does NOT set `$isScopedToTenant = false` — same
 * convention as every other tenant-owned resource (CategoryResource, StoreResource, etc).
 */
class LandingPageResource extends Resource
{
    protected static ?string $model = LandingPage::class;

    protected static ?string $navigationIcon = 'heroicon-o-newspaper';
    protected static ?string $navigationLabel = 'Best X Pages';
    protected static ?string $navigationGroup = 'Product Management';
    protected static ?int $navigationSort = 7;

    public static function form(Form $form): Form
    {
        return $form->schema([
            Forms\Components\Section::make('Landing Page')
                ->columns(2)
                ->schema([
                    Forms\Components\Select::make('category_id')
                        ->label('Category')
                        ->options(fn () => Category::doesntHave('children')->pluck('name', 'id'))
                        ->searchable()
                        ->required()
                        ->unique(ignoreRecord: true)
                        ->helperText('One landing page per (leaf) category.'),
                    Forms\Components\TextInput::make('slug')
                        ->required()
                        ->maxLength(255)
                        ->unique(ignoreRecord: true)
                        ->helperText('Permanent — do not change after publishing (Spec 027 §3: URL accrues links across years).'),
                    Forms\Components\TextInput::make('title_template')
                        ->label('Title Override')
                        ->maxLength(255)
                        ->helperText('Optional. Leave blank to use the computed "The {N} Best {Category} in {Year} — Ranked by Data" title.')
                        ->columnSpanFull(),
                    Forms\Components\Toggle::make('status')
                        ->label('Published')
                        ->helperText('On = live at /best/{slug}. Off = draft (not publicly visible). Publishing here does NOT re-run AI generation.')
                        ->formatStateUsing(fn (?string $state) => $state === 'published')
                        ->dehydrateStateUsing(fn (bool $state) => $state ? 'published' : 'draft'),
                    Forms\Components\DateTimePicker::make('generated_at')
                        ->label('Last Generated')
                        ->disabled()
                        ->dehydrated(),
                ]),

            Forms\Components\Section::make('Content')
                ->schema([
                    Forms\Components\Textarea::make('intro')
                        ->label('Intro (AI-generated HTML)')
                        ->rows(6)
                        ->helperText('Generate/refresh via: php artisan pw2d:generate-landing-page {tenant} {category-slug} --regenerate')
                        ->columnSpanFull(),

                    Forms\Components\Repeater::make('picks')
                        ->label('Ranked Picks')
                        ->helperText('Picks (product + role) are chosen algorithmically and are read-only here — only the prose is editable. Re-run the command with --regenerate to change WHICH products are picked.')
                        ->schema([
                            Forms\Components\TextInput::make('product_id')
                                ->label('Product ID')
                                ->numeric()
                                ->disabled()
                                ->dehydrated(),
                            Forms\Components\TextInput::make('role')
                                ->disabled()
                                ->dehydrated(),
                            Forms\Components\TextInput::make('headline')
                                ->required()
                                ->maxLength(150)
                                ->columnSpanFull(),
                            Forms\Components\Textarea::make('body')
                                ->rows(4)
                                ->columnSpanFull(),
                        ])
                        ->columns(2)
                        ->itemLabel(function (array $state): ?string {
                            $productName = !empty($state['product_id'])
                                ? Product::withoutGlobalScopes()->find($state['product_id'])?->name
                                : null;

                            return trim(($state['role'] ?? '?') . ' — ' . ($productName ?? 'product #' . ($state['product_id'] ?? '?')));
                        })
                        ->addable(false)
                        ->deletable(false)
                        ->reorderable(false)
                        ->collapsible()
                        ->columnSpanFull(),

                    Forms\Components\Repeater::make('faqs')
                        ->label('FAQs')
                        ->helperText('4-6 entries recommended. Must not duplicate compare-page/preset FAQs.')
                        ->schema([
                            Forms\Components\TextInput::make('question')
                                ->required()
                                ->columnSpanFull(),
                            Forms\Components\Textarea::make('answer')
                                ->required()
                                ->rows(3)
                                ->columnSpanFull(),
                        ])
                        ->collapsible()
                        ->defaultItems(0)
                        ->columnSpanFull(),

                    Forms\Components\Textarea::make('methodology_note')
                        ->label('Methodology Note')
                        ->rows(2)
                        ->helperText('Plain text — appended to the static "How we ranked" block.')
                        ->columnSpanFull(),
                ])
                ->columnSpanFull(),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('category.name')
                    ->label('Category')
                    ->searchable()
                    ->sortable(),
                Tables\Columns\TextColumn::make('slug')
                    ->color('gray')
                    ->searchable(),
                Tables\Columns\TextColumn::make('status')
                    ->badge()
                    ->color(fn (string $state) => $state === 'published' ? 'success' : 'gray')
                    ->sortable(),
                Tables\Columns\TextColumn::make('generated_at')
                    ->label('Generated')
                    ->dateTime()
                    ->sortable()
                    ->placeholder('Never'),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('status')
                    ->options(['draft' => 'Draft', 'published' => 'Published']),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index'  => Pages\ListLandingPages::route('/'),
            'create' => Pages\CreateLandingPage::route('/create'),
            'edit'   => Pages\EditLandingPage::route('/{record}/edit'),
        ];
    }
}
