<?php

declare(strict_types=1);

namespace App\Filament\Resources;

use App\Filament\Resources\LandingPageResource\Pages;
use App\Models\Category;
use App\Models\LandingPage;
use App\Models\Product;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Cache;

/**
 * Minimal v1 admin for "Best X" landing pages (Spec 027 §8).
 *
 * Pages are generated by `pw2d:generate-landing-page` — this resource exists so
 * an owner can review a draft, tweak intro/pick prose/FAQs, and PUBLISH without
 * re-running AI generation (the publish toggle is a plain status write, no AI
 * call). Picks are algorithmically selected (App\Actions\SelectLandingPagePicks)
 * so the repeater only allows editing the AI-written prose per pick, not adding/
 * removing/reordering rows — that would silently break the "picks are chosen by
 * DATA, not by the AI/admin" guarantee the whole page's E-E-A-T claim rests on.
 *
 * Tenant-scoped automatically: `LandingPage` uses `BelongsToTenant`, and (unlike
 * `TenantResource`) this resource does NOT set `$isScopedToTenant = false` — same
 * convention as every other tenant-owned resource (CategoryResource, StoreResource, etc).
 */
class LandingPageResource extends Resource
{
    protected static ?string $model = LandingPage::class;

    protected static ?string $navigationIcon = 'heroicon-o-newspaper';
    protected static ?string $navigationLabel = 'Best X Pages';
    protected static ?string $navigationGroup = 'Product Management';
    protected static ?int $navigationSort = 7;

    /**
     * Spec 030 §B5 — count of stale PUBLISHED pages for the current tenant.
     * Cached briefly (matches ProblemProducts::getNavigationBadge()'s 120s TTL)
     * and tenant-scoped by key, since LandingPage::query() itself is already
     * scoped to the ambient tenant (BelongsToTenant).
     */
    public static function getNavigationBadge(): ?string
    {
        // Security L1: without an initialized tenant, `staleQuery()` runs UNSCOPED
        // (stancl's BelongsToTenant global scope is inactive) and the cache key would
        // degenerate to a shared `...badge:` entry across every central-context
        // request — an all-tenants count leak. Skip the badge entirely instead.
        if (tenant('id') === null) {
            return null;
        }

        $count = Cache::remember(
            'landing-pages-stale-badge:' . tenant('id'),
            120,
            fn () => static::staleQuery()->count(),
        );

        return $count > 0 ? (string) $count : null;
    }

    public static function getNavigationBadgeColor(): ?string
    {
        return 'danger';
    }

    private static function staleQuery(): Builder
    {
        return LandingPage::query()
            ->where('status', 'published')
            ->whereNotNull('stale_reasons')
            ->where('stale_reasons', '!=', '[]');
    }

    public static function form(Form $form): Form
    {
        return $form->schema([
            Forms\Components\Section::make('Landing Page')
                ->columns(2)
                ->schema([
                    Forms\Components\Select::make('category_id')
                        ->label('Category')
                        ->options(fn () => Category::doesntHave('children')->pluck('name', 'id'))
                        ->searchable()
                        ->required()
                        ->unique(ignoreRecord: true)
                        ->helperText('One landing page per (leaf) category.'),
                    Forms\Components\TextInput::make('slug')
                        ->required()
                        ->maxLength(255)
                        ->unique(ignoreRecord: true)
                        ->helperText('Permanent — do not change after publishing (Spec 027 §3: URL accrues links across years).'),
                    Forms\Components\TextInput::make('title_template')
                        ->label('Title Override')
                        ->maxLength(255)
                        ->helperText('Optional. Leave blank to use the computed "The {N} Best {Category} in {Year} — Ranked by Data" title.')
                        ->columnSpanFull(),
                    Forms\Components\Toggle::make('status')
                        ->label('Published')
                        ->helperText('On = live at /best/{slug}. Off = draft (not publicly visible). Publishing here does NOT re-run AI generation.')
                        ->formatStateUsing(fn (?string $state) => $state === 'published')
                        ->dehydrateStateUsing(fn (bool $state) => $state ? 'published' : 'draft'),
                    Forms\Components\DateTimePicker::make('generated_at')
                        ->label('Last Generated')
                        ->disabled()
                        ->dehydrated(),
                ]),

            Forms\Components\Section::make('Content')
                ->schema([
                    Forms\Components\Textarea::make('intro')
                        ->label('Intro (AI-generated HTML)')
                        ->rows(6)
                        ->helperText('Generate/refresh via: php artisan pw2d:generate-landing-page {tenant} {category-slug} --regenerate')
                        ->columnSpanFull(),

                    Forms\Components\Repeater::make('picks')
                        ->label('Ranked Picks')
                        ->helperText('Picks (product + role) are chosen algorithmically and are read-only here — only the prose is editable. Re-run the command with --regenerate to change WHICH products are picked.')
                        ->schema([
                            // Security M3 / Reviewer B3: `disabled()` alone is client-
                            // tamperable via a crafted Livewire update payload — these
                            // fields are shown for admin context only and are NEVER
                            // trusted on save. `dehydrated(false)` means they don't even
                            // reach $data; identity fields (product_id/role) AND
                            // est_price_snapshot are then force-restored from the
                            // STORED record in EditLandingPage::mutateFormDataBeforeSave(),
                            // so a tampered payload can never change WHICH product a pick
                            // points at, its role, or wipe its price-drift baseline.
                            Forms\Components\TextInput::make('product_id')
                                ->label('Product ID')
                                ->numeric()
                                ->disabled()
                                ->dehydrated(false),
                            Forms\Components\TextInput::make('role')
                                ->disabled()
                                ->dehydrated(false),
                            Forms\Components\TextInput::make('headline')
                                ->required()
                                ->maxLength(150)
                                ->columnSpanFull(),
                            Forms\Components\Textarea::make('body')
                                ->rows(4)
                                ->columnSpanFull(),
                        ])
                        ->columns(2)
                        ->itemLabel(function (array $state): ?string {
                            // Perf M3 / Security M3: `product_name` is persisted into the
                            // picks JSON at generation time (GenerateLandingPage) — zero
                            // queries per render. Falls back to a TENANT-SCOPED lookup
                            // (never withoutGlobalScopes(), which could disclose another
                            // tenant's product name) only for pre-existing pages
                            // generated before this field existed.
                            $productName = $state['product_name']
                                ?? (!empty($state['product_id']) ? Product::find($state['product_id'])?->name : null);

                            return trim(($state['role'] ?? '?') . ' — ' . ($productName ?? 'product #' . ($state['product_id'] ?? '?')));
                        })
                        ->addable(false)
                        ->deletable(false)
                        ->reorderable(false)
                        ->collapsible()
                        ->columnSpanFull(),

                    Forms\Components\Repeater::make('faqs')
                        ->label('FAQs')
                        ->helperText('4-6 entries recommended. Must not duplicate compare-page/preset FAQs.')
                        ->schema([
                            Forms\Components\TextInput::make('question')
                                ->required()
                                ->columnSpanFull(),
                            Forms\Components\Textarea::make('answer')
                                ->required()
                                ->rows(3)
                                ->columnSpanFull(),
                        ])
                        ->collapsible()
                        ->defaultItems(0)
                        ->columnSpanFull(),

                    Forms\Components\Textarea::make('methodology_note')
                        ->label('Methodology Note')
                        ->rows(2)
                        ->helperText('Plain text — appended to the static "How we ranked" block.')
                        ->columnSpanFull(),
                ])
                ->columnSpanFull(),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('category.name')
                    ->label('Category')
                    ->searchable()
                    ->sortable(),
                Tables\Columns\TextColumn::make('slug')
                    ->color('gray')
                    ->searchable(),
                Tables\Columns\TextColumn::make('status')
                    ->badge()
                    ->color(fn (string $state) => $state === 'published' ? 'success' : 'gray')
                    ->sortable(),
                Tables\Columns\TextColumn::make('freshness')
                    ->label('Freshness')
                    ->badge()
                    ->getStateUsing(fn (LandingPage $record) => empty($record->stale_reasons) ? 'FRESH' : 'STALE')
                    ->color(fn (LandingPage $record) => empty($record->stale_reasons) ? 'success' : 'danger')
                    ->description(fn (LandingPage $record) => empty($record->stale_reasons) ? null : implode(', ', $record->stale_reasons))
                    ->tooltip(fn (LandingPage $record) => empty($record->stale_reasons)
                        ? 'No staleness reasons — picks, prices, and render count all match.'
                        : implode(', ', $record->stale_reasons)),
                Tables\Columns\TextColumn::make('generated_at')
                    ->label('Generated')
                    ->dateTime()
                    ->sortable()
                    ->placeholder('Never'),
            ])
            // Spec 030 §B5: stale + published pages need eyes on them first.
            ->defaultSort(fn (Builder $query) => $query
                ->orderByRaw("CASE WHEN status = 'published' AND stale_reasons IS NOT NULL AND stale_reasons != '[]' THEN 0 ELSE 1 END")
                ->orderBy('status', 'desc'))
            ->filters([
                Tables\Filters\SelectFilter::make('status')
                    ->options(['draft' => 'Draft', 'published' => 'Published']),
                Tables\Filters\TernaryFilter::make('stale')
                    ->label('Freshness')
                    ->placeholder('All')
                    ->trueLabel('Stale only')
                    ->falseLabel('Fresh only')
                    ->queries(
                        true: fn (Builder $query) => $query->whereNotNull('stale_reasons')->where('stale_reasons', '!=', '[]'),
                        false: fn (Builder $query) => $query->where(fn (Builder $q) => $q->whereNull('stale_reasons')->orWhere('stale_reasons', '[]')),
                    ),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index'  => Pages\ListLandingPages::route('/'),
            'create' => Pages\CreateLandingPage::route('/create'),
            'edit'   => Pages\EditLandingPage::route('/{record}/edit'),
        ];
    }
}
